# This file is a template, and might need editing before it works on your project.
# see https://docs.gitlab.com/ce/ci/yaml/README.html for all available options

before_script:
   
   
after_script:

   
build-release:
 tags:
   - win32
 stage: build
 script:
   - powershell echo "Building"
   - powershell -ExecutionPolicy bypass -File utils/build.ps1
 artifacts:
  paths:
    - ./*

Release:
 tags:
   - win32
 stage: deploy
 script:
   - powershell echo "Do your deploy here"
   - powershell ls
   - powershell src
   - powershell ls src/tmp
   - powershell mkdir elsplus
   - powershell cp -R src/tmp/* elsplus
   - powershell -ExecutionPolicy bypass -File utils/publish.ps1
 artifacts:
  name: ELS_FiveM-0.0.3.2-gitlab_$CI_JOB_ID
  paths:
    - elsplus/*