# This file is a template, and might need editing before it works on your project.
# see https://docs.gitlab.com/ce/ci/yaml/README.html for all available options

before_script:
   
   
after_script:

   
build-release:
 tags:
   - win32
 stage: build
 script:
   - echo "Building"
   - utils/build.ps1
 artifacts:
  paths:
    - ./*

Release:
 tags:
   - win32
 stage: deploy
 script:
   - echo "Do your deploy here"
   - ls
   - ls src
   - ls src/tmp
   - mkdir elsplus
   - cp -R src/tmp/* elsplus
 artifacts:
  name: ELS_FiveM-0.0.3.2-gitlab_$CI_JOB_ID
  paths:
    - elsplus/*