# This file is a template, and might need editing before it works on your project.
# see https://docs.gitlab.com/ce/ci/yaml/README.html for all available options

# you can delete this line if you're not using Docker
image: mono:latest

before_script:
   
   
after_script:

   
build1:
 stage: build
 script:
   - echo "Building"
   - cd src
   - xbuild /p:outDir=tmp/ /p:Configuration=Release /p:PostBuildEvent= /t:Build ELS-for-FiveM.sln
 artifacts:
  paths:
    - src/tmp

   
test1:
 stage: test
 script: 
   - echo "Do a test here"
   
test2:
 stage: test
 script: 
   - echo "Do another parallel test here"
   - echo "For example run a lint test"

deploy1:
 stage: deploy
 script:
   - echo "Do your deploy here"
   - ls
   - ls src
   - ls src/tmp
   - mkdir ELS_FiveM-$version-gitlab_$CI_JOB_ID
   - cp -R src/tmp/* ELS_FiveM-$version-gitlab_$CI_JOB_ID
   - cp README.md LICESE.txt docs ELS_FiveM-$version-gitlab_$CI_JOB_ID/
 artifacts:
  name: "ELS_FiveM-$version-gitlab_$CI_JOB_ID"
  paths:
    - ELS_FiveM-$version-gitlab_$CI_JOB_ID/*